import type {
  NavItem,
  PersonaItem,
  ProvisioningLog,
  RecommendationRequest,
  RunHistory,
  SoftwareItem,
  SummaryCardData,
} from "./types";

export const navItems: NavItem[] = [
  { id: "overview", label: "Overview", section: "Platform", icon: "⊞" },
  { id: "workbench", label: "Bundle Workbench", section: "Platform", icon: "⌘" },
  { id: "cleansing", label: "Data Cleansing", section: "Agents", icon: "⛁", badge: 4 },
  { id: "personas", label: "Persona Management", section: "Agents", icon: "⊕" },
  { id: "provisioning", label: "Provisioning", section: "Agents", icon: "⚡" },
  { id: "newjoiner", label: "New Joiner Portal", section: "End User", icon: "⊗" },
  { id: "reports", label: "Reports & Analytics", section: "Admin", icon: "⊠" },
  { id: "settings", label: "Settings", section: "Admin", icon: "⚙" },
];

export const overviewCards: SummaryCardData[] = [
  { label: "Total Personas", value: "8", subtext: "Current mapped cohort archetypes", accent: "var(--red)" },
  { label: "Software Catalogue", value: "15", subtext: "Prototype main package catalogue", accent: "var(--purple)" },
  { label: "Users Provisioned", value: "8", subtext: "Recent sample activity", accent: "var(--green)" },
  { label: "Pending HITL", value: "5", subtext: "Awaiting human review", accent: "var(--amber)" },
];

export const softwareCatalogue: SoftwareItem[] = [
  {
    id: "SW01",
    publisher: "Microsoft",
    name: "Microsoft Office 365",
    version: "16.0",
    category: "Main Package",
    deploymentType: "Standard",
    confidence: 98,
    status: "Confirmed",
  },
  {
    id: "SW02",
    publisher: "Adobe",
    name: "Adobe Acrobat Pro DC",
    version: "23.6",
    category: "Main Package",
    deploymentType: "Recommended",
    confidence: 95,
    status: "Confirmed",
  },
  {
    id: "SW03",
    publisher: "Autodesk",
    name: "AutoCAD",
    version: "2024.0",
    category: "Main Package",
    deploymentType: "Finance/SAM-Approved",
    confidence: 92,
    status: "Confirmed",
  },
  {
    id: "SW04",
    publisher: "Microsoft",
    name: "Microsoft Visio",
    version: "16.0",
    category: "Main Package",
    deploymentType: "Manager-Approved",
    confidence: 88,
    status: "Confirmed",
  },
  {
    id: "SW05",
    publisher: "Tableau",
    name: "Tableau Desktop",
    version: "2024.1",
    category: "Main Package",
    deploymentType: "Finance/SAM-Approved",
    confidence: 85,
    status: "Pending",
  },
  {
    id: "SW06",
    publisher: "Slack",
    name: "Slack",
    version: "4.37",
    category: "Main Package",
    deploymentType: "Pre-Approved",
    confidence: 97,
    status: "Confirmed",
  },
  {
    id: "SW07",
    publisher: "Zoom",
    name: "Zoom Workplace",
    version: "6.0",
    category: "Main Package",
    deploymentType: "Pre-Approved",
    confidence: 96,
    status: "Confirmed",
  },
  {
    id: "SW08",
    publisher: "Salesforce",
    name: "Salesforce CRM",
    version: "248.0",
    category: "Main Package",
    deploymentType: "Manager-Approved",
    confidence: 72,
    status: "Pending",
  },
];

export const personas: PersonaItem[] = [
  {
    id: "P001",
    department: "Facilities Management",
    title: "Facilities Manager",
    standardTitle: "Facilities Manager",
    role: "Operations",
    subgroup: "Facility Ops",
    family: "Property & Asset Mgmt",
    users: 47,
    confidence: "High",
    bundleStatus: "Validated",
    modifiedAt: "2026-03-15",
    bundle: {
      base: ["Windows 11 Enterprise", "Microsoft Edge", "Microsoft Defender"],
      standard: ["Microsoft Office 365", "Microsoft Teams", "Slack", "Zoom Workplace", "Citrix Workspace"],
      recommended: ["Adobe Acrobat Pro DC", "Microsoft Visio", "Bluebeam Revu", "Microsoft Project"],
      optional: ["AutoCAD", "Tableau Desktop", "WinZip"],
    },
  },
  {
    id: "P002",
    department: "Project Management",
    title: "Senior Project Manager",
    standardTitle: "Project Manager",
    role: "Delivery",
    subgroup: "Project Delivery",
    family: "Project Mgmt",
    users: 32,
    confidence: "High",
    bundleStatus: "Validated",
    modifiedAt: "2026-03-12",
    bundle: {
      base: ["Windows 11 Enterprise", "Microsoft Edge", "Microsoft Defender"],
      standard: ["Microsoft Office 365", "Microsoft Teams", "Slack", "Zoom Workplace", "Citrix Workspace"],
      recommended: ["Adobe Acrobat Pro DC", "Microsoft Visio", "Bluebeam Revu", "Microsoft Project"],
      optional: ["AutoCAD", "Tableau Desktop", "WinZip"],
    },
  },
  {
    id: "P003",
    department: "Finance",
    title: "Financial Analyst",
    standardTitle: "Financial Analyst",
    role: "Finance",
    subgroup: "Financial Planning",
    family: "Finance",
    users: 28,
    confidence: "High",
    bundleStatus: "Validated",
    modifiedAt: "2026-03-10",
    bundle: {
      base: ["Windows 11 Enterprise", "Microsoft Edge", "Microsoft Defender"],
      standard: ["Microsoft Office 365", "Microsoft Teams", "Slack", "Zoom Workplace", "Citrix Workspace"],
      recommended: ["Adobe Acrobat Pro DC", "Microsoft Visio", "Bluebeam Revu", "Microsoft Project"],
      optional: ["AutoCAD", "Tableau Desktop", "WinZip"],
    },
  },
  {
    id: "P004",
    department: "IT",
    title: "Solutions Architect",
    standardTitle: "Solutions Architect",
    role: "Technology",
    subgroup: "Architecture",
    family: "Technology",
    users: 12,
    confidence: "High",
    bundleStatus: "Validated",
    modifiedAt: "2026-03-08",
    bundle: {
      base: ["Windows 11 Enterprise", "Microsoft Edge", "Microsoft Defender"],
      standard: ["Microsoft Office 365", "Microsoft Teams", "Slack", "Zoom Workplace", "Citrix Workspace"],
      recommended: ["Adobe Acrobat Pro DC", "Microsoft Visio", "Bluebeam Revu", "Microsoft Project"],
      optional: ["AutoCAD", "Tableau Desktop", "WinZip"],
    },
  },
];

export const provisioningLogs: ProvisioningLog[] = [
  {
    id: "PL01",
    timestamp: "2026-03-27T09:15:00Z",
    user: "USR-7821",
    department: "Facilities Management",
    title: "Facilities Coordinator",
    personaId: "P001",
    match: "Exact",
    mode: "Interactive",
    total: 7,
    preApproved: 3,
    managerApproved: 3,
    financeApproved: 1,
    status: "Completed",
    software: ["Adobe Acrobat Pro DC", "Microsoft Visio", "Bluebeam Revu", "Slack", "Zoom", "Microsoft Project", "AutoCAD"],
  },
  {
    id: "PL02",
    timestamp: "2026-03-26T14:30:00Z",
    user: "USR-4392",
    department: "IT",
    title: "Cloud Engineer",
    personaId: "P004",
    match: "Nearest",
    mode: "Interactive",
    total: 6,
    preApproved: 3,
    managerApproved: 2,
    financeApproved: 1,
    status: "Completed",
    software: ["VS Code", "IntelliJ IDEA", "Slack", "Zoom", "Microsoft Visio", "Tableau"],
  },
  {
    id: "PL03",
    timestamp: "2026-03-26T11:00:00Z",
    user: "USR-5518",
    department: "Finance",
    title: "Sr Financial Analyst",
    personaId: "P003",
    match: "Exact",
    mode: "Silent",
    total: 5,
    preApproved: 3,
    managerApproved: 2,
    financeApproved: 0,
    status: "Completed",
    software: ["Adobe Acrobat Pro DC", "Slack", "Zoom", "Tableau Desktop", "WinZip"],
  },
];

export const runHistory: RunHistory[] = [
  {
    id: "CR01",
    type: "Full",
    date: "2026-03-01",
    records: 143405,
    status: "Completed",
    duration: "1h 47m",
    mainPackages: 48602,
    filtered: 94803,
  },
  {
    id: "CR02",
    type: "Delta",
    date: "2026-03-08",
    records: 2341,
    status: "Completed",
    duration: "8m 12s",
    mainPackages: 812,
    filtered: 1529,
  },
  {
    id: "CR03",
    type: "Delta",
    date: "2026-03-15",
    records: 1876,
    status: "Completed",
    duration: "6m 45s",
    mainPackages: 645,
    filtered: 1231,
  },
];

export const bundleFormDefaults: RecommendationRequest = {
  title: "Facilities Manager",
  function: "Facilities Management",
  businessCategory: "Work Dynamics",
  region: "APAC",
  account: "Corporate",
};

export const personaBundles = {
  base: ["Windows 11 Enterprise", "Microsoft Edge", "Microsoft Defender"],
  standard: ["Microsoft Office 365", "Microsoft Teams", "Slack", "Zoom Workplace", "Citrix Workspace"],
  recommended: ["Adobe Acrobat Pro DC", "Microsoft Visio", "Bluebeam Revu", "Microsoft Project"],
  optional: ["AutoCAD", "Tableau Desktop", "WinZip"],
};
